spring:
  application:
    name: api-gateway
info:
  author: mafei
  app: ${spring.application.name}
server:
  port: 8080

eureka:
  instance:
    preferIpAddress: false
    hostname: localhost
    instance-id: "${random.uuid}:${spring.application.name}"
    metadata-map:
      node: node1
      timestamp: ${APP_TIMESTAMP}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
    healthcheck:
      enabled: true
    should-unregister-on-shutdown: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
      discovery:
        enabled: true
endpoints:
  shutdown:
    enabled: true


