spring:
  application:
    name: user-service
info:
  author: mafei
  app: ${spring.application.name}
server:
  port: 0

eureka:
  instance:
    preferIpAddress: true
    instance-id: "${random.uuid}:${spring.application.name}"
    metadata-map:
      node: node1
      timestamp: ${APP_TIMESTAMP}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8070/eureka/}
    healthcheck:
      enabled: true
    should-unregister-on-shutdown: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
      discovery:
        enabled: true
endpoints:
  shutdown:
    enabled: true


